.TH "parolottero" 6 "Aug 09, 2022" "Word composition game"
.SH "NAME"
parolottero \(em Compose words from a grid of letters
.SH "SYNOPSIS"
.PP
\fBparolottero\fR

.SH "DESCRIPTION"
.PP
This is a word composition game.
.br
Players must choose a language, then drag their finger (or mouse) over the letters on the screen to compose as many words as possible before the time is over.
.br
The seed lets users repeat a game. It can be used to do multiplayer, if players all agree on a seed.
.SH "REPORTING BUGS"
.PP
Report all bugs here: <https://github.com/ltworf/parolottero>
.br
To report bugs on words you can enable bug reporting. Edit `~/.config/Parolottero/Parolottero.conf` and enable. You should use your own github token rather than the provided one.
.br
The token requires the public_repo permission.
.SH "AUTHOR"
.PP
Written by Salvo "LtWorf" Tomaselli

.SH "COPYRIGHT"
.PP
Copyright © 2022 Salvo "LtWorf" Tomaselli. License AGPLv3: GNU Affero GPL version 3 <https://gnu.org/licenses/agpl.html>.
This is free software: you are free to change and redistribute it.  There is NO WARRANTY, to the extent permitted by law.
